#!/usr/bin/env bash
# Install nginx web server and configures it
sudo apt-get update -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" > /usr/share/nginx/html/index.html
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dphzDKZa6xk permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
